name: dispatch-when-update-master-branch
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: package-version-to-git-tag
        uses: pkgdeps/action-package-version-to-git-tag@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"
      - name: dispatch update-packages
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: github_name/repo
          token: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
          event-type: update-pkgs