name: dispatch-when-update-master-branch
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: dispatch Update-frontend-component workflow on frontend repo
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: operation-check-for-GHorganization/frontend
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: update-frontend-component