name: dispatch-when-update-master-branch
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: dispatch update-packages
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: cc-sato/base
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: update-pkgs